name: Deploy to Lightsail

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Build Go server
      - name: Build Go server
        run: |
          cd server/cmd/chat-server
          go build -o server-binary

      # Build React frontend
      - name: Build frontend
        run: |
          cd client
          npm ci
          npm run build

      # Upload files
      - name: Release files to AWS Lightsail VPS
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          source: "server/server-binary,client/dist/*"          
          target: "/home/builds/webchat_build_artifacts"

      # Move files and restart services
      - name: Deploy and Restart
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            sudo mv /home/builds/webchat_build_artifacts/server/server-binary /opt/bitnami/apps/webchat/bin/server
            sudo rm -rf /opt/bitnami/nginx/html/*
            sudo cp -r /home/ubuntu/app/client/build/* /opt/bitnami/nginx/html/
            sudo systemctl restart webchat
            sudo /opt/bitnami/ctlscript.sh restart nginx
